# Generated by Django 5.0.1 on 2024-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='download_1.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
