# Generated by Django 5.0.1 on 2024-04-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_user'),
        ('pricing', '0012_remove_planprice_duration_plan_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_plan', to='pricing.plan'),
        ),
    ]
