# Generated by Django 5.0.1 on 2024-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
