# Generated by Django 5.0.1 on 2024-04-18 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 10, 46, 38, 773465, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 10, 46, 38, 773465, tzinfo=datetime.timezone.utc)),
        ),
    ]
