# Generated by Django 5.0.1 on 2024-04-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
    ]
