# Generated by Django 5.0.1 on 2024-04-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_planprice_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprice',
            name='price',
        ),
    ]
