# Generated by Django 5.0.1 on 2024-04-18 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pricing.feature'),
        ),
    ]
