# Generated by Django 5.0.1 on 2024-04-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_remove_feature_plan_plan_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.feature'),
        ),
    ]
