# Generated by Django 5.0.1 on 2024-04-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_plan_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='feature',
        ),
        migrations.AddField(
            model_name='plan',
            name='feature',
            field=models.ManyToManyField(to='pricing.feature'),
        ),
    ]
