# Generated by Django 5.0.1 on 2024-04-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_remove_plan_feature_plan_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='feature',
        ),
        migrations.AddField(
            model_name='feature',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pricing.plan'),
        ),
    ]
