# Generated by Django 5.0.1 on 2024-04-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprice',
            name='duration',
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=1, help_text='duration in months'),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.plan'),
        ),
    ]
