# Generated by Django 5.0.1 on 2024-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_remove_planprice_duration_plan_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planprice',
            options={'verbose_name': 'PlanPrice', 'verbose_name_plural': 'PlanPrices'},
        ),
        migrations.AddField(
            model_name='planprice',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
