# Generated by Django 5.0.1 on 2024-04-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_alter_planprice_options_planprice_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planprice',
            name='end_date',
        ),
    ]
