# Generated by Django 5.0.1 on 2024-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_remove_planprice_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='chat_room_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited rooms'),
        ),
    ]
